### ISSUE TITLE
unmaintained repo?

### ISSUE THREAD

**Issue by tom42530** [hebcal/hebcal-java#1]
Hi,

Thanks for your job.

I see that the repo hasn't been touched for 10 years. is it still relevant?

 what is your recommendation for native android integration?

Thanks in advance

**Comment by mjradwin** [comment]
You are correct, this repo is not actively maintained. 

Try KosherJava

https://github.com/KosherJava/zmanim

**Comment by tom42530** [comment]
Thanks for the response.

I will try that
